/*
 * Mini projet de CPO (2A), 2020
 * Par  Lucas DELMOTTE, Clara THEODOLY et Émile ROYER
 * Implémentation de jeu « Labyrinthe »
 */
package labyrinthe;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Lucas DELMOTTE, Clara THEODOLY et Émile ROYER
 */
public class FenetreDeJeu extends javax.swing.JFrame {

	// variables utilisées pour le chrono
	int nbSecondes = 0;
	Timer monChrono;
	Plateau PlateauJeu = new Plateau();

	// insertion de l'image pour notre chrono
	ImageIcon img_iconetimer = new javax.swing.ImageIcon(getClass().getResource("/images/timer.png"));
	// insertion de l'image pour les boutons de chaques cotés du plateau
	ImageIcon img_fleched = new javax.swing.ImageIcon(getClass().getResource("/images/fleched.png"));
	ImageIcon img_flecheg = new javax.swing.ImageIcon(getClass().getResource("/images/flecheg.png"));
	ImageIcon img_flecheh = new javax.swing.ImageIcon(getClass().getResource("/images/flecheh.png"));
	ImageIcon img_flecheb = new javax.swing.ImageIcon(getClass().getResource("/images/flecheb.png"));

	public FenetreDeJeu() {
		initComponents();

		// création du chrono
		ActionListener tache_recurrente = new ActionListener() {
			public void actionPerformed(ActionEvent e1) {
				nbSecondes++; // incrémentation du nombres de seconde
				texte_temps.setText(nbSecondes + "");
			};
		};

        /* Instanciation du timer */
		monChrono = new Timer(1000, tache_recurrente);
		iconeTimer.setIcon(img_iconetimer); // création de la petite image avec le chrono
		/* ajout des images aux divers boutons*/
		jouer_versdroite_ligne2.setIcon(img_fleched);
		jouer_versdroite_ligne4.setIcon(img_fleched);
		jouer_versdroite_ligne6.setIcon(img_fleched);

		jouer_versgauche_ligne2.setIcon(img_flecheg);
		jouer_versgauche_ligne4.setIcon(img_flecheg);
		jouer_versgauche_ligne6.setIcon(img_flecheg);

		jouer_versbas_col2.setIcon(img_flecheb);
		jouer_versbas_col4.setIcon(img_flecheb);
		jouer_versbas_col6.setIcon(img_flecheb);

		jouer_vershaut_col2.setIcon(img_flecheh);
		jouer_vershaut_col4.setIcon(img_flecheh);
		jouer_vershaut_col6.setIcon(img_flecheh);

		Infojeu.setVisible(false);
		panneauGrille.setVisible(true);
		panel_tuilevolante.setVisible(false);
		panel_joueur.setVisible(false);
		panel_chrono.setVisible(false);

		/* Dialogue modal du nombre de joueurs */
		jLabel22.setVisible(false);
		nom_joueur2_dia.setVisible(false);
		jLabel23.setVisible(false);
		nom_joueur3_dia.setVisible(false);
		jLabel20.setVisible(false);
		nom_joueur4_dia.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize
	 * the form. WARNING: Do NOT modify this code. The content of this
	 * method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        dialogueJoueurs = new javax.swing.JDialog();
        nbJoueurs_dia = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        nom_joueur4_dia = new javax.swing.JTextField();
        nom_joueur1_dia = new javax.swing.JTextField();
        nom_joueur2_dia = new javax.swing.JTextField();
        nom_joueur3_dia = new javax.swing.JTextField();
        btn_start3 = new javax.swing.JButton();
        texterandom = new javax.swing.JLabel();
        panneauGrille = new javax.swing.JPanel();
        Infojeu = new javax.swing.JPanel();
        panel_tuilevolante = new javax.swing.JPanel();
        imgTuileVolante = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panel_joueur = new javax.swing.JPanel();
        NomJcourant = new javax.swing.JLabel();
        objectif_courant = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        objectif_restants = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        NomJcourant1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel_chrono = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        texte_temps = new javax.swing.JLabel();
        iconeTimer = new javax.swing.JLabel();
        jouer_versbas_col6 = new javax.swing.JButton();
        jouer_vershaut_col2 = new javax.swing.JButton();
        jouer_vershaut_col4 = new javax.swing.JButton();
        jouer_vershaut_col6 = new javax.swing.JButton();
        jouer_versbas_col2 = new javax.swing.JButton();
        jouer_versbas_col4 = new javax.swing.JButton();
        jouer_versgauche_ligne6 = new javax.swing.JButton();
        jouer_versdroite_ligne6 = new javax.swing.JButton();
        jouer_versdroite_ligne4 = new javax.swing.JButton();
        jouer_versdroite_ligne2 = new javax.swing.JButton();
        jouer_versgauche_ligne2 = new javax.swing.JButton();
        jouer_gauche_ligne7 = new javax.swing.JButton();
        jouer_versgauche_ligne4 = new javax.swing.JButton();
        affDialogueJoueurs = new javax.swing.JButton();

        jTextField2.setText("jTextField1");

        dialogueJoueurs.setMinimumSize(new java.awt.Dimension(500, 500));
        dialogueJoueurs.setModal(true);
        dialogueJoueurs.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nbJoueurs_dia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        nbJoueurs_dia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nbJoueurs_diaStateChanged(evt);
            }
        });
        dialogueJoueurs.getContentPane().add(nbJoueurs_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 60, -1));

        jLabel19.setText("Combien de personnes jouent ?");
        dialogueJoueurs.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel20.setText("Nom du joueur 4 :");
        dialogueJoueurs.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, -1));

        jLabel21.setText("Nom du joueur 1 :");
        dialogueJoueurs.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 130, -1));

        jLabel22.setText("Nom du joueur 2 :");
        dialogueJoueurs.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 130, -1));

        jLabel23.setText("Nom du joueur 3 :");
        dialogueJoueurs.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, -1));
        dialogueJoueurs.getContentPane().add(nom_joueur4_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, -1));
        dialogueJoueurs.getContentPane().add(nom_joueur1_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 120, -1));
        dialogueJoueurs.getContentPane().add(nom_joueur2_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 120, -1));
        dialogueJoueurs.getContentPane().add(nom_joueur3_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 120, -1));

        btn_start3.setText("Démarrer la partie");
        btn_start3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start3ActionPerformed(evt);
            }
        });
        dialogueJoueurs.getContentPane().add(btn_start3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        texterandom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texterandom.setText("1 joueur jouera");
        dialogueJoueurs.getContentPane().add(texterandom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1170, 715));
        setPreferredSize(new java.awt.Dimension(1170, 715));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneauGrille.setBackground(new java.awt.Color(255, 255, 255));
        panneauGrille.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(panneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 567, 567));

        Infojeu.setBackground(new java.awt.Color(204, 204, 204));
        Infojeu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Infojeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 210, 330));

        panel_tuilevolante.setBackground(new java.awt.Color(204, 204, 204));
        panel_tuilevolante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_tuilevolante.add(imgTuileVolante, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 81, 81));

        jButton3.setText("rotation");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel_tuilevolante.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 80, 30));

        jLabel16.setText("Cliquez sur le bouton de rotation");
        panel_tuilevolante.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabel17.setText("pour faire pivoter la tuile de 90°");
        panel_tuilevolante.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        getContentPane().add(panel_tuilevolante, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 210, 210));

        panel_joueur.setBackground(new java.awt.Color(255, 255, 255));
        panel_joueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomJcourant.setText("Jcourant");
        panel_joueur.add(NomJcourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 10));

        objectif_courant.setBackground(new java.awt.Color(102, 102, 255));
        objectif_courant.setText("jLabel1");
        panel_joueur.add(objectif_courant, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 84, 137));

        jLabel2.setText("Il vous reste encore");
        panel_joueur.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 120, -1));

        objectif_restants.setText("objectif_restants");
        panel_joueur.add(objectif_restants, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 120, -1));

        jLabel1.setText("objectif(s)");
        panel_joueur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        panel_joueur.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 140, 10));

        jLabel3.setText("Le joueur courant est :");
        panel_joueur.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        NomJcourant1.setText("Jcourant");
        panel_joueur.add(NomJcourant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 10));

        jButton1.setText("Commencer le tour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_joueur.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 130, -1));

        jButton2.setText("Terminer le tour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel_joueur.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, -1));

        getContentPane().add(panel_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 250, 330));

        panel_chrono.setBackground(new java.awt.Color(204, 204, 204));
        panel_chrono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("temps écoulé");
        panel_chrono.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 20));

        texte_temps.setText("0");
        panel_chrono.add(texte_temps, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 30, -1));
        panel_chrono.add(iconeTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 36, 40));

        getContentPane().add(panel_chrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 250, 210));

        jouer_versbas_col6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_versbas_col6ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_versbas_col6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 30, 30));

        jouer_vershaut_col2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_vershaut_col2ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_vershaut_col2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 630, 30, 30));

        jouer_vershaut_col4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_vershaut_col4ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_vershaut_col4, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 630, 30, 30));

        jouer_vershaut_col6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_vershaut_col6ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_vershaut_col6, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 630, 30, 30));

        jouer_versbas_col2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_versbas_col2ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_versbas_col2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 10, 30, 30));

        jouer_versbas_col4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_versbas_col4ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_versbas_col4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 10, 30, 30));

        jouer_versgauche_ligne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_versgauche_ligne6ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_versgauche_ligne6, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 480, 30, 30));

        jouer_versdroite_ligne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_versdroite_ligne6ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_versdroite_ligne6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 30, 30));

        jouer_versdroite_ligne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_versdroite_ligne4ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_versdroite_ligne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 318, 30, 30));

        jouer_versdroite_ligne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_versdroite_ligne2ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_versdroite_ligne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, 30, 30));

        jouer_versgauche_ligne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_versgauche_ligne2ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_versgauche_ligne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 156, 30, 30));

        jouer_gauche_ligne7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_gauche_ligne7ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_gauche_ligne7, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 156, 30, 30));

        jouer_versgauche_ligne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jouer_versgauche_ligne4ActionPerformed(evt);
            }
        });
        getContentPane().add(jouer_versgauche_ligne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 318, 30, 30));

        affDialogueJoueurs.setText("Afficher le dialogue");
        affDialogueJoueurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affDialogueJoueursActionPerformed(evt);
            }
        });
        getContentPane().add(affDialogueJoueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jouer_versbas_col6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_versbas_col6ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_versbas_col6ActionPerformed

    private void jouer_vershaut_col2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_vershaut_col2ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_vershaut_col2ActionPerformed

    private void jouer_vershaut_col4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_vershaut_col4ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_vershaut_col4ActionPerformed

    private void jouer_vershaut_col6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_vershaut_col6ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_vershaut_col6ActionPerformed

    private void jouer_versbas_col2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_versbas_col2ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_versbas_col2ActionPerformed

    private void jouer_versbas_col4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_versbas_col4ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_versbas_col4ActionPerformed

    private void jouer_versgauche_ligne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_versgauche_ligne6ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_versgauche_ligne6ActionPerformed

    private void jouer_versdroite_ligne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_versdroite_ligne6ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_versdroite_ligne6ActionPerformed

    private void jouer_versdroite_ligne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_versdroite_ligne4ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_versdroite_ligne4ActionPerformed

    private void jouer_versdroite_ligne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_versdroite_ligne2ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_versdroite_ligne2ActionPerformed

    private void jouer_versgauche_ligne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_versgauche_ligne2ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_versgauche_ligne2ActionPerformed

    private void jouer_gauche_ligne7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_gauche_ligne7ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_gauche_ligne7ActionPerformed

    private void jouer_versgauche_ligne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jouer_versgauche_ligne4ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jouer_versgauche_ligne4ActionPerformed

    private void btn_start3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start3ActionPerformed
		dialogueJoueurs.dispose();
                Infojeu.setVisible(true);
		panneauGrille.setVisible(true);
		panel_tuilevolante.setVisible(true);
		panel_joueur.setVisible(true);
		panel_chrono.setVisible(true);
         
    }//GEN-LAST:event_btn_start3ActionPerformed

    private void nbJoueurs_diaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nbJoueurs_diaStateChanged
		int nbJoueurs = (int) nbJoueurs_dia.getValue();
		switch (nbJoueurs) {
			case 1:
				texterandom.setText("1 joueur jouera");
				jLabel21.setVisible(true);
				nom_joueur1_dia.setVisible(true);
				jLabel22.setVisible(false);
				nom_joueur2_dia.setVisible(false);
				jLabel23.setVisible(false);
				nom_joueur3_dia.setVisible(false);
				jLabel20.setVisible(false);
				nom_joueur4_dia.setVisible(false);
				break;
			case 2:
				texterandom.setText("2 joueurs joueront");
				jLabel21.setVisible(true);
				nom_joueur1_dia.setVisible(true);
				jLabel22.setVisible(true);
				nom_joueur2_dia.setVisible(true);
				jLabel23.setVisible(false);
				nom_joueur3_dia.setVisible(false);
				jLabel20.setVisible(false);
				nom_joueur4_dia.setVisible(false);
				break;
			case 3:
				texterandom.setText("3 joueurs joueront");
				jLabel21.setVisible(true);
				nom_joueur1_dia.setVisible(true);
				jLabel22.setVisible(true);
				nom_joueur2_dia.setVisible(true);
				jLabel23.setVisible(true);
				nom_joueur3_dia.setVisible(true);
				jLabel20.setVisible(false);
				nom_joueur4_dia.setVisible(false);
				break;
			case 4:
				texterandom.setText("4 joueurs joueront");
				jLabel21.setVisible(true);
				nom_joueur1_dia.setVisible(true);
				jLabel22.setVisible(true);
				nom_joueur2_dia.setVisible(true);
				jLabel23.setVisible(true);
				nom_joueur3_dia.setVisible(true);
				jLabel20.setVisible(true);
				nom_joueur4_dia.setVisible(true);
				break;
		}
    }//GEN-LAST:event_nbJoueurs_diaStateChanged

    private void affDialogueJoueursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affDialogueJoueursActionPerformed
		dialogueJoueurs.setVisible(true);
    }//GEN-LAST:event_affDialogueJoueursActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FenetreDeJeu().setVisible(true);
			}
		});
	}

	/* public final void ajouterTuilesGraphiques() {
        for (int i = 0; i < PlateauJeu.nb_lignes; i++) {
            for (int j = 0; j < PlateauJeu.nb_colonnes; j++) {
                ... A ADAPTER POUR LA CRATION DES TUILE GRAPHIQUE DU LAYOUT
                CelluleGraphique cellGraph = new CelluleGraphique(grilleJeu.Cellules[i][j]); // création d'une nouvelle cellule graphique appelé cellGraph

                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Cellule c = cellGraph.celluleAssociee;
                        if (c.jetonCourant == null) {
                            texte_message.setText("");
                            return;
                        }
                        if (c.jetonCourant.Couleur.equals(joueurCourant.Couleur)) {
                            texte_message.setText(joueurCourant.Nom + " récupère un de ses jetons");
                            Jeton j_recup = c.recupererJeton();
                            c.supprimerJeton();
                            joueurCourant.ajouterJeton(j_recup);
                            joueurSuivant();
                        } else {
                            if (joueurCourant.nombreDesintegrateurs > 0) {
                                texte_message.setText(joueurCourant.Nom + " désintègre un jeton adverse");
                                c.supprimerJeton();
                                joueurCourant.utiliserDesintegrateur();
                                joueurSuivant();
                            }
                        }
                        grilleJeu.tasserGrille();
                        actualiserAffichage();
                    }
                });
                panneau_grille.add(cellGraph); // on ajoute les éléments cellGraph à notre panneau de jeu
            }
        }
    }
	 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Infojeu;
    private javax.swing.JLabel NomJcourant;
    private javax.swing.JLabel NomJcourant1;
    private javax.swing.JButton affDialogueJoueurs;
    private javax.swing.JButton btn_start3;
    private javax.swing.JDialog dialogueJoueurs;
    private javax.swing.JLabel iconeTimer;
    private javax.swing.JLabel imgTuileVolante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jouer_gauche_ligne7;
    private javax.swing.JButton jouer_versbas_col2;
    private javax.swing.JButton jouer_versbas_col4;
    private javax.swing.JButton jouer_versbas_col6;
    private javax.swing.JButton jouer_versdroite_ligne2;
    private javax.swing.JButton jouer_versdroite_ligne4;
    private javax.swing.JButton jouer_versdroite_ligne6;
    private javax.swing.JButton jouer_versgauche_ligne2;
    private javax.swing.JButton jouer_versgauche_ligne4;
    private javax.swing.JButton jouer_versgauche_ligne6;
    private javax.swing.JButton jouer_vershaut_col2;
    private javax.swing.JButton jouer_vershaut_col4;
    private javax.swing.JButton jouer_vershaut_col6;
    private javax.swing.JSpinner nbJoueurs_dia;
    private javax.swing.JTextField nom_joueur1_dia;
    private javax.swing.JTextField nom_joueur2_dia;
    private javax.swing.JTextField nom_joueur3_dia;
    private javax.swing.JTextField nom_joueur4_dia;
    private javax.swing.JLabel objectif_courant;
    private javax.swing.JLabel objectif_restants;
    private javax.swing.JPanel panel_chrono;
    private javax.swing.JPanel panel_joueur;
    private javax.swing.JPanel panel_tuilevolante;
    private javax.swing.JPanel panneauGrille;
    private javax.swing.JLabel texte_temps;
    private javax.swing.JLabel texterandom;
    // End of variables declaration//GEN-END:variables
}
